baseURL: http://localhost:1313/
languageCode: zh-cn
title: 你好！我是周晓彤
theme: air

# 支持多语言
defaultContentLanguage: zh-cn

params:
  author:
    name: 张艺术家
    siteUrl: https://example.com/
  # 主题色
  mainColor: "#2563eb"
  # 页脚信息
  footer: "© 2025 张艺术家 - 个人作品展示"

menu:
  main:
    - name: 关于我
      url: /about/
      weight: 10
    - name: 作品集
      url: /portfolio/
      weight: 20
    - name: 图
      url: /portfolio/visual/
      parent: 作品集
      weight: 21
    - name: 文
      url: /portfolio/writing/
      parent: 作品集
      weight: 22
    - name: 视频
      url: /portfolio/video/
      parent: 作品集
      weight: 23
    - name: 运营案例
      url: /operation-cases/
      weight: 30

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true